---
repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v4.3.0
      hooks:
          - id: trailing-whitespace
          - id: end-of-file-fixer
            exclude: js/bootstrap4/resources/
          - id: fix-encoding-pragma
            args: [--remove]
          - id: check-yaml
          - id: debug-statements
            language_version: python3
    - repo: https://github.com/PyCQA/flake8
      rev: 5.0.4
      hooks:
          - id: flake8
            language_version: python3
    - repo: https://github.com/pre-commit/mirrors-autopep8
      rev: v2.0.0
      hooks:
          - id: autopep8
    - repo: https://github.com/PyCQA/isort
      rev: 5.10.1
      hooks:
      - id: isort
        args: [--filter-files]
        files: \.py$
    - repo: local
      hooks:
          - id: rst
            name: rst
            entry: rst-lint --encoding utf-8
            files: .rst
            language: python
            additional_dependencies: [pygments, restructuredtext_lint]
