language: python
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7-dev"
install:
  - pip install setuptools --upgrade
  - python bootstrap.py
  - bin/buildout
script: bin/py.test js/bootstrap4/test_bootstrap.txt
